### PR TITLE
Enhance: dress color generation

### PR DESCRIPTION
**Pull request by Shivansh-007**
The original color generations were really close and non differentiable due to which it looked the man duck wore a night suit xD. Now we use the duck body color to generate triad, therefore the three colors can never be similar :D

### Earlier
e69d0a4af7d16d569a1193144410ff2a8a8d4998

### Now
0771ae4f981891eacabd76f7cfe9b4e1fb9cb166

### CODE REVIEW

**Comment by mbaruh** [comment]
I'm not sure what you mean by the "eariler" image, the ninja suit is meant to be all-black.

**Comment by Shivansh-007** [comment]
> I'm not sure what you mean by the "eariler" image, the ninja suit is meant to be all-black.

Oops yeah, here you go

Also for some reason, the flake8 works perfectly on mine but fails here, I will commit the change according to the flake8 error raised on workflow.

E5002541-195E-47C4-9F37-246759340B8B

**Comment by mbaruh** [comment]
What's up with the beak on that duck? it looks as if the templates aren't applied in the right order

**Review by vcokltfre — APPROVED** [review]
LGTM! Beak overlaying like that is definitely an issue but that's in ducky generation so we'll deal with that after

**Pull request merged**
